### ISSUE TITLE
Prepare for release v1.8 minor release

### ISSUE THREAD

**Issue by adilGhaffarDev** [metal3-io/cluster-api-provider-metal3#1887]
Here we can track the tasks related to release 1.8

## Tasks

* [x] Prepare dev-env to acommodate new release related changes and configurations [Prior art](https://github.com/metal3-io/metal3-dev-env/pull/1381)
  * [x] PR: https://github.com/metal3-io/metal3-dev-env/pull/1443
  * [x] PR: https://github.com/metal3-io/metal3-dev-env/pull/1452
* [x] Release Ironic, also check new image is created in quay. [Prior art](https://github.com/metal3-io/ironic-image/tags)
  * [x] v26.0.0 release: https://github.com/metal3-io/ironic-image/releases/tag/v26.0.0
* [x] Pin Ironic in BMO and metal3-dev-env. [Prior art](https://github.com/metal3-io/baremetal-operator/pull/1679) 
  * [x] PR: https://github.com/metal3-io/baremetal-operator/pull/1928
  * [x] PR: https://github.com/metal3-io/metal3-dev-env/pull/1453
* [x] Uplift CAPI to v1.8.1 in IPAM and CAPM3, also check migration guide: [Migration guide for providers](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/book/src/developer/providers/migrations/v1.7-to-v1.8.md) . [Prior art IPAM](https://github.com/metal3-io/ip-address-manager/pull/497), [Prior art CAPM3](https://github.com/metal3-io/cluster-api-provider-metal3/pull/1604)
  * [x] IPAM bump PR: https://github.com/metal3-io/ip-address-manager/pull/641 
  * [x] CAPM3 bump PR: https://github.com/metal3-io/cluster-api-provider-metal3/pull/1889
  * [x] CAPM3 related to CAPI uplift: https://github.com/metal3-io/cluster-api-provider-metal3/pull/1883
* [x] Uplift k8s to 1.31 in CAPM3 and metal3-dev-env repo. [Prior art metal3-dev-env](https://github.com/metal3-io/metal3-dev-env/pull/1389), [Prior art CAPM3](https://github.com/metal3-io/cluster-api-provider-metal3/pull/1622)
  * [x] dev-env PR: https://github.com/metal3-io/metal3-dev-env/pull/1444
  * [x] CAPM3 PR: https://github.com/metal3-io/cluster-api-provider-metal3/pull/1866
* [x] Uplift k8s to 1.31 in image building pipeline. [Pending PR](https://github.com/metal3-io/baremetal-operator/pull/1928)
  * [x] PR updating jjb: https://gerrit.nordix.org/c/infra/cicd/+/22205
  * [x] PR updating pipeline: https://github.com/metal3-io/project-infra/pull/836
* [x] Release IPAM (Branch out, add branch protection and required tests, also check new image is created in quay).
  * [x] Branched out: https://github.com/metal3-io/ip-address-manager/tree/release-1.8
  * [x] Create release TODO. 
* [x] Release BMO (Branch out, add branch protection and required tests, also check new image is created in quay).
  * [x] Branched out: https://github.com/metal3-io/baremetal-operator/tree/release-0.8
  * [x] Create release TODO.
* [x] Bump IPAM and BMO in CAPM3 in both main and release-1.8 [Prior art](https://github.com/metal3-io/cluster-api-provider-metal3/pull/1605)
  * [x] https://github.com/metal3-io/cluster-api-provider-metal3/pull/1944
  * [x] https://github.com/metal3-io/cluster-api-provider-metal3/pull/1946
* [x] Release CAPM3 (Branch out, add branch protection and required tests, also check new image is created in quay).
  * [x] Branched out: https://github.com/metal3-io/cluster-api-provider-metal3/tree/release-1.8  
* [x] Add/edit JJBs to accommodate new build jobs and PR jobs for new release branches. And remove unsupported releases tests for CAPM3 and IPAM. [Prior art](https://gerrit.nordix.org/c/infra/cicd/+/20875)
  * [x] jjb PR: https://gerrit.nordix.org/c/infra/cicd/+/22187
* [x] Add Prow jobs for new release branches in Project-infra repo, also remove unsupported releases tests for CAPM3 and IPAM here too [Prior art](https://github.com/metal3-io/project-infra/pull/697)
  * [x] Pipeline update PR:https://github.com/metal3-io/project-infra/pull/832
* [x] Check CI if new releases are tested properly or not
* [x] Update CAPM3 README.md with the new e2e triggers, on both the release-1.8 and on main [Prior art](https://github.com/metal3-io/cluster-api-provider-metal3/pull/1618)
  * [x] https://github.com/metal3-io/cluster-api-provider-metal3/pull/1956
  * [x] https://github.com/metal3-io/cluster-api-provider-metal3/pull/1955
* [x] Update IPAM README.md with the new e2e triggers, on both the release-1.8 and on main [Prior art](https://github.com/metal3-io/ip-address-manager/pull/504)
  * [x] https://github.com/metal3-io/ip-address-manager/pull/677
  * [x] https://github.com/metal3-io/ip-address-manager/pull/678
* [x] Update BMO README.md with the new e2e triggers, on both the release-0.8 and on main  [Prior art](https://github.com/metal3-io/baremetal-operator/pull/1694)
  * [x] https://github.com/metal3-io/baremetal-operator/pull/1933
  * [x] https://github.com/metal3-io/baremetal-operator/pull/1934
* [x] Add BMO upgrade test for release-0.8 -> main, and update all ironic upgrade tests to use release-0.8, also remove tests for release-0.4
  - https://github.com/metal3-io/baremetal-operator/pull/1945
* [x] Update Metal3 book. [Prior art](https://github.com/metal3-io/metal3-docs/pull/413)
  - https://github.com/metal3-io/metal3-docs/pull/469 
  - https://github.com/metal3-io/metal3-docs/pull/467
* [x] Announce the releases

## Post-release tasks
Do the following on the main branch after the release is done. 

* [x] Add CAPI v1.8 contract. 
   - [x] PR: https://github.com/metal3-io/cluster-api-provider-metal3/pull/1888 
* [x] Update clusterctl tests to accommodate new releases.
   - [x] PR: https://github.com/metal3-io/cluster-api-provider-metal3/pull/2057

**Comment by Sunnatillo** [comment]
k8s uplift for node images: https://github.com/metal3-io/project-infra/pull/836
CAPI uplift: https://github.com/metal3-io/ip-address-manager/pull/641
CAPI uplift: https://github.com/metal3-io/cluster-api-provider-metal3/pull/1889

**Comment by Sunnatillo** [comment]
opened Draft PR in dev env for release 1.8 related changes: 
https://github.com/metal3-io/metal3-dev-env/pull/1448

**Comment by tuminoid** [comment]
https://github.com/metal3-io/cluster-api-provider-metal3/pull/1891
https://github.com/metal3-io/cluster-api-provider-metal3/pull/1890
https://github.com/metal3-io/ip-address-manager/pull/642
https://github.com/metal3-io/baremetal-operator/pull/1886
https://github.com/metal3-io/baremetal-operator/pull/1883
https://github.com/metal3-io/baremetal-operator/pull/1882
https://github.com/metal3-io/ip-address-manager/pull/645
https://github.com/metal3-io/ip-address-manager/pull/644
https://github.com/metal3-io/ip-address-manager/pull/643
https://github.com/metal3-io/baremetal-operator/pull/1885
https://github.com/metal3-io/baremetal-operator/pull/1884
https://github.com/metal3-io/cluster-api-provider-metal3/pull/1885

and perhaps some cherry-picks of those coming still.

**Comment by tuminoid** [comment]
https://github.com/metal3-io/cluster-api-provider-metal3/pull/1892

**Comment by tuminoid** [comment]
https://github.com/metal3-io/cluster-api-provider-metal3/pull/1893

**Comment by tuminoid** [comment]
https://github.com/metal3-io/baremetal-operator/pull/1888 + cherry-picks coming

**Comment by tuminoid** [comment]
BMO releasing complete
- https://github.com/metal3-io/baremetal-operator/releases/tag/v0.8.0
- https://github.com/metal3-io/baremetal-operator/releases/tag/v0.6.2
- https://github.com/metal3-io/baremetal-operator/releases/tag/v0.5.2

**Comment by adilGhaffarDev** [comment]
all done, closing this issue.
