### ISSUE TITLE
Prepare for release v1.9 minor release

### ISSUE THREAD

**Issue by mquhuy** [metal3-io/cluster-api-provider-metal3#2137]
Here we can track the tasks related to release 1.9

## Tasks

* [x] Prepare dev-env to acommodate new release related changes and configurations. Prior art: [1](https://github.com/metal3-io/metal3-dev-env/pull/1443),  [2](https://github.com/metal3-io/metal3-dev-env/pull/1452)
   * [x] PR: https://github.com/metal3-io/metal3-dev-env/pull/1485  
* [x] Release Ironic, also check new image is created in quay. Prior art: [v26.0.0 release](https://github.com/metal3-io/ironic-image/releases/tag/v26.0.0)
* [x] Pin Ironic in BMO. [Prior art](https://github.com/metal3-io/baremetal-operator/pull/1928)
* [x] Pin Ironic in metal3-dev-env. [Prior art](https://github.com/metal3-io/metal3-dev-env/pull/1453)
* [x] Uplift CAPI to v1.9.0 in IPAM and CAPM3, also check migration guide: [Migration guide for providers](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/book/src/developer/providers/migrations/v1.7-to-v1.8.md) . [Prior art IPAM](https://github.com/metal3-io/ip-address-manager/pull/641), [Prior art CAPM3](https://github.com/metal3-io/cluster-api-provider-metal3/pull/1889)
* [x] Uplift k8s to 1.32 in CAPM3 repo. [Prior art](https://github.com/metal3-io/cluster-api-provider-metal3/pull/1866)
   * [x] PR: https://github.com/metal3-io/cluster-api-provider-metal3/pull/2158  
* [x] Uplift k8s to 1.32 in metal3-dev-env repo. [Prior art](https://github.com/metal3-io/metal3-dev-env/pull/1444)
   * [x] PR: https://github.com/metal3-io/metal3-dev-env/pull/1484 
* [x] Uplift k8s to 1.32 in image building pipeline. Prior art: [1](https://gerrit.nordix.org/c/infra/cicd/+/22205), [2](https://github.com/metal3-io/project-infra/pull/836)
   * [x] PR: https://github.com/metal3-io/project-infra/pull/929 
* [x] Release IPAM (Make release note PR, also check new image is created in quay).
   * [x] https://github.com/metal3-io/ip-address-manager/releases/tag/v1.9.1 
* [x] Check if BMO needs release. If so, release BMO (Branch out, add branch protection and required tests, also check new image is created in quay). [Prior art](https://github.com/metal3-io/baremetal-operator/tree/release-0.8)
   * [x] https://github.com/metal3-io/baremetal-operator/releases/tag/v0.9.0
* [x] Bump IPAM and BMO in CAPM3 in main [Prior art](https://github.com/metal3-io/cluster-api-provider-metal3/pull/1605)
  * [x] PR: https://github.com/metal3-io/metal3-dev-env/pull/2170
* [x] Release CAPM3 (Branch out, add branch protection and required tests, also check new image is created in quay).
  * [x] https://github.com/metal3-io/cluster-api-provider-metal3/releases/tag/v1.9.0
* [x] Add/edit JJBs to accommodate new build jobs and PR jobs for new release branches. And remove unsupported releases tests for CAPM3 and IPAM. [Prior art](https://gerrit.nordix.org/c/infra/cicd/+/20875)
  * [x] PR adding 1.9 jobs: https://gerrit.nordix.org/c/infra/cicd/+/22800
  * [x] PR removing 1.6 jobs: https://gerrit.nordix.org/c/infra/cicd/+/22802 
* [x] Add Prow jobs for new release branches in Project-infra repo, also remove unsupported releases tests for CAPM3 and IPAM here too [Prior art](https://github.com/metal3-io/project-infra/pull/697)
  * [x] PR IPAM: https://github.com/metal3-io/project-infra/pull/931
  * [x] PR BMO: https://github.com/metal3-io/project-infra/pull/933
  * [x] PR CAPM3: https://github.com/metal3-io/project-infra/pull/934
  * [x] PR remove 1.6 tests: https://github.com/metal3-io/project-infra/pull/935
  * [x] PR add triggers to other repos: https://github.com/metal3-io/project-infra/pull/936
* [x] Check CI if new releases are tested properly or not
* [x] Update CAPM3 README.md with the new e2e triggers, on both the release-1.9 and on main. Prior art: [1](https://github.com/metal3-io/cluster-api-provider-metal3/pull/1956), [2](https://github.com/metal3-io/cluster-api-provider-metal3/pull/1955)
  * [x] PR main: https://github.com/metal3-io/cluster-api-provider-metal3/pull/2232 
  * [x] PR release-1.9: https://github.com/metal3-io/cluster-api-provider-metal3/pull/2185
* [x] Update IPAM README.md with the new e2e triggers, on both the release-1.9 and on main. Prior art: [1](https://github.com/metal3-io/ip-address-manager/pull/677), [2](https://github.com/metal3-io/ip-address-manager/pull/678)
  * [x] PR release-1.9: https://github.com/metal3-io/ip-address-manager/pull/813
* [x] Update BMO README.md with the new e2e triggers, on both the release-0.9 (if applicable) and on main. Prior art: [1](https://github.com/metal3-io/baremetal-operator/pull/1933), [2](https://github.com/metal3-io/baremetal-operator/pull/1934)
  * [x] PR main: https://github.com/metal3-io/baremetal-operator/pull/2134 
  * [x]  PR release-0.9: https://github.com/metal3-io/baremetal-operator/pull/2175
* [x] Add BMO upgrade test for release-0.9 -> main, and update all ironic upgrade tests to use release-0.9, also remove tests for release-0.5 [Prior art](https://github.com/metal3-io/baremetal-operator/pull/1945)
  * [x] PR: https://github.com/metal3-io/baremetal-operator/pull/2134  
* [x] Update Metal3 book. Prior art: [1](https://github.com/metal3-io/metal3-docs/pull/469), [2](https://github.com/metal3-io/metal3-docs/pull/467)
  * [x] PR: https://github.com/metal3-io/metal3-docs/pull/491
* [x] Announce the releases

## Post-release tasks
Do the following on the main branch after the release is done. 

* [x] Add CAPI v1.9 contract. [Prior art](https://github.com/metal3-io/cluster-api-provider-metal3/pull/1888)
  * [x] PR: https://github.com/metal3-io/cluster-api-provider-metal3/pull/2164 
* [x] Update clusterctl tests to accommodate new releases. [Prior Art](https://github.com/metal3-io/cluster-api-provider-metal3/pull/2057)
  * [x] PR: https://github.com/metal3-io/cluster-api-provider-metal3/pull/2164 
  * [x] PR: https://github.com/metal3-io/cluster-api-provider-metal3/pull/2242

**Comment by tuminoid** [comment]
CI prepping PRs: JJB, Prow, contracts, dev-env etc:
- https://gerrit.nordix.org/c/infra/cicd/+/22800 
- https://gerrit.nordix.org/c/infra/cicd/+/22802 
- https://github.com/metal3-io/project-infra/pull/931 
- https://github.com/metal3-io/metal3-dev-env/pull/1485 
- https://github.com/metal3-io/project-infra/pull/933 
- https://github.com/metal3-io/project-infra/pull/934 
- https://github.com/metal3-io/project-infra/pull/935 
- https://github.com/metal3-io/metal3-docs/pull/491 
- https://github.com/metal3-io/project-infra/pull/936 
- https://github.com/metal3-io/cluster-api-provider-metal3/pull/2164 
- https://github.com/metal3-io/baremetal-operator/pull/2135
- https://github.com/metal3-io/cluster-api-provider-metal3/pull/2165 
- https://github.com/Nordix/metal3-dev-tools/pull/778

**Comment by kashifest** [comment]
whats left here @adilGhaffarDev @mquhuy @peppi-lotta

**Comment by peppi-lotta** [comment]
Ticks in the task list should be up to date. 

> whats left here @adilGhaffarDev @mquhuy @peppi-lotta

The task list is up to date: only one PR is waiting to be merged and then everything is done.

**Comment by kashifest** [comment]
> The task list is up to date: only one PR is waiting to be merged and then everything is done.

I think we have announced the release, so we can tick that as well. 

![Screenshot 2025-01-14 at 14 36 26](https://github.com/user-attachments/assets/a76d1aca-3c32-42a0-bdff-a9a631716314)

**Comment by mquhuy** [comment]
/close
Every item is ticked.
