### ISSUE TITLE
Bump API version to v1beta1 [Tracking Issue] 

### ISSUE THREAD

**Issue by furkatgofurov7** [metal3-io/cluster-api-provider-metal3#322]
**Describe the solution you'd like**

- Bump API version to **v1beta1** to match Cluster API Core

**Anything else you would like to add:**

xref: [v1alpha4 -> v1beta1 changes for providers CAPI documentation](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/book/src/developer/providers/v1alpha4-to-v1beta1.md)

**Rough task list:**
- [x] https://github.com/metal3-io/cluster-api-provider-metal3/issues/314
- [x] https://github.com/metal3-io/cluster-api-provider-metal3/issues/315
- [x] https://github.com/metal3-io/cluster-api-provider-metal3/issues/316
- [x] https://github.com/metal3-io/cluster-api-provider-metal3/issues/317
- [x] https://github.com/metal3-io/cluster-api-provider-metal3/issues/318
- [x] https://github.com/metal3-io/cluster-api-provider-metal3/issues/319
- [x] https://github.com/metal3-io/cluster-api-provider-metal3/issues/320
- [x] https://github.com/metal3-io/cluster-api-provider-metal3/issues/321

**Related issues upstream:**
- https://github.com/kubernetes-sigs/cluster-api/issues/5260
- https://github.com/kubernetes-sigs/cluster-api/issues/5262
- https://github.com/kubernetes-sigs/cluster-api/issues/5269
- https://github.com/kubernetes-sigs/cluster-api/issues/5277
- https://github.com/kubernetes-sigs/cluster-api/issues/5281

/kind feature

**Comment by furkatgofurov7** [comment]
This is a tracking issue and should be closed automatically once child issue https://github.com/metal3-io/cluster-api-provider-metal3/issues/319 is closed.

**Comment by furkatgofurov7** [comment]
This was a tracking issue and all the issues inside are closed now, so closing this one as well.

/close
