### ISSUE TITLE
Removal of v1alpha5 apiversion

### ISSUE THREAD

**Issue by kashifest** [metal3-io/cluster-api-provider-metal3#971]
## Motivation

v1alpha5(v0.5.x) apiVersion have been EOL since September 2022 and the equivalent CAPI apiVersion v1alpha4(v0.4.x) has been EOL since April 2022. It is now a good time to plan to remove v1alpha5.

## Proposal
We can follow the following timeline:

- Release v1.5:
   -  Announce removal of apiVersion in v1.6 & v1.7
- Release v1.6:
   - Kubernetes API server will stop serving v1alpha5
      - We will set `served` to `false` for the apiVersion in all our CRDs.
      - Then users can’t read or write with the old apiVersion anymore.
      - The API server will still be able to read and convert the old apiVersion.
      - If necessary, users can easily enable the apiVersion again by reverting `served `back to `true` on the CRD.   
 - Release v1.7:
    - Remove v1alpha5 apiVersion
       - Drop all code related to v1alpha5 (API types, conversions, tests, …)
       - If we get feedback that folks need more time to migrate we can discuss delaying this stage by another minor release to give folks more time.

## Tasks

- [x] Open a PR to document removal plan
- [x] Check with CAPI maintainers if providers also need to implement changes as they have done in https://github.com/kubernetes-sigs/cluster-api/issues/7224 and https://github.com/kubernetes-sigs/cluster-api/pull/7995.

v1.5:

- [x] Mark v1alpha5 apiVersion and Go API types as deprecated
- [x] Release notes should highlight the imminent removal of the apiVersion in v1.6 & v1.7

v1.6:

- [x] Stop serving v1alpha5 via `kubebuilder:unservedversion`
- [x]  Release notes should reflect the changes

v1.7:

- [x] Drop all code related to v1alpha5 (API types, conversion, …)
   - Wait a bit for feedback after v1.6
- [x]  Release notes should reflect the changes

Misc:

- [x] Upgrade tests should be updated to cover v1.1 => v1.latest:
- [x] Document upgrade test coverage

/kind cleanup

**Comment by Rozzii** [comment]
/cc @adilGhaffarDev 
@adilGhaffarDev has commented on https://github.com/kubernetes-sigs/cluster-api/issues/10051 thus linking it with https://github.com/kubernetes-sigs/cluster-api/issues/9688 FYI. I guess this requires a CAPI side fix anyways .

**Comment by kashifest** [comment]
@adilGhaffarDev actually this issue is done, since we removed the API already, I forgot to update it, can you describe a bit more in detail whats the issue here since in the removal of API PR we agreed that it should not affect us https://github.com/metal3-io/cluster-api-provider-metal3/pull/1525#issuecomment-1996763856. Also from community side we dont have any issue reported yet on this so we can safely assume no one was using the v1a5 API?

**Comment by kashifest** [comment]
This issue is good to close since the API is removed already, if we see any further issues I suggest we create a separate issue for that. 
/close
